# Generated by Django 4.2.7 on 2023-11-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='lab',
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='professor',
            name='lab_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.ImageField(default=0, upload_to='professor_photos'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
