# Generated by Django 4.2.7 on 2023-11-30 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_rename_lab_number_professor_lab_alter_professor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='lab',
            new_name='lab_number',
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
