# Generated by Django 4.2.7 on 2023-11-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_lab_professor_lab_number_alter_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
