# Generated by Django 4.2.7 on 2023-12-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_assistant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
    ]
