# Generated by Django 4.2.7 on 2023-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_timetable_end_time_timetable_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
