# Generated by Django 4.2.7 on 2023-12-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_appointment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
