# Generated by Django 4.2.7 on 2023-12-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_roomreservation_professor_roomreservation_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomreservation',
            name='professor',
        ),
    ]
