# Generated by Django 4.2.7 on 2023-12-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_roomreservation_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='student',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
        migrations.AddField(
            model_name='appointment',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.professor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
        migrations.AddField(
            model_name='roomreservation',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assistant'),
        ),
    ]
