# Generated by Django 4.2.7 on 2023-12-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_student_roomreservation_requester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='equipment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assistant'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
