# Generated by Django 4.2.7 on 2023-12-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_reservation_equipment_reservation_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
    ]
